/*
# Multi-Agent Product Development Platform Schema

## Overview
Creates the full data model for an AI-powered product development platform where
a multi-agent team (Requirements, PM, Architect, UI/UX) collaborates with a human
operator through a chat interface to take a product from raw requirements to
technical architecture.

## New Tables

1. **projects** — Top-level container for a product development session.
   - `id` (uuid PK)
   - `name` (text) — project title
   - `problem_statement` (text) — raw input from the human operator
   - `current_stage` (text) — tracks pipeline stage: 'discovery' | 'decomposition' | 'architecture' | 'design' | 'complete'
   - `created_at`, `updated_at` (timestamps)

2. **messages** — Chat messages between human and agents.
   - `id` (uuid PK)
   - `project_id` (FK → projects)
   - `agent_type` (text) — 'human' | 'requirements' | 'pm' | 'architect' | 'uiux'
   - `content` (text) — message body (markdown for agents)
   - `metadata` (jsonb) — optional structured payload (e.g. checkpoint type)
   - `created_at` (timestamp)

3. **prds** — Product Requirement Documents generated by the Requirements Agent.
   - `id` (uuid PK)
   - `project_id` (FK → projects)
   - `content` (text) — full PRD in markdown
   - `status` (text) — 'draft' | 'pending_review' | 'approved'
   - `created_at`, `updated_at`

4. **epics** — High-level epics decomposed by the PM Agent.
   - `id` (uuid PK)
   - `project_id` (FK → projects)
   - `title` (text)
   - `description` (text)
   - `status` (text) — 'pending' | 'in_progress' | 'done'
   - `created_at`

5. **tasks** — Granular technical tasks under each epic.
   - `id` (uuid PK)
   - `epic_id` (FK → epics)
   - `project_id` (FK → projects, for easier queries)
   - `title` (text)
   - `description` (text)
   - `status` (text) — 'pending' | 'in_progress' | 'done'
   - `created_at`

6. **diagrams** — Mermaid.js DFD diagrams generated by the Architect Agent.
   - `id` (uuid PK)
   - `project_id` (FK → projects)
   - `title` (text)
   - `mermaid_syntax` (text) — raw mermaid graph definition
   - `created_at`

7. **ui_components** — React/Tailwind component code generated by the UI/UX Agent.
   - `id` (uuid PK)
   - `project_id` (FK → projects)
   - `title` (text)
   - `code` (text) — component source code
   - `framework` (text) — 'react' | 'html' | etc.
   - `created_at`

## Security
- RLS enabled on all tables.
- Single-tenant (no auth): policies use `TO anon, authenticated` with `USING (true)`
  because the data is intentionally shared/public within this workspace.
*/

-- Projects
CREATE TABLE IF NOT EXISTS projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT 'Untitled Project',
  problem_statement text DEFAULT '',
  current_stage text NOT NULL DEFAULT 'discovery',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_projects" ON projects;
CREATE POLICY "anon_select_projects" ON projects FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_projects" ON projects;
CREATE POLICY "anon_insert_projects" ON projects FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_projects" ON projects;
CREATE POLICY "anon_update_projects" ON projects FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_projects" ON projects;
CREATE POLICY "anon_delete_projects" ON projects FOR DELETE TO anon, authenticated USING (true);

-- Messages
CREATE TABLE IF NOT EXISTS messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  agent_type text NOT NULL DEFAULT 'human',
  content text NOT NULL DEFAULT '',
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_messages_project_id ON messages(project_id);

DROP POLICY IF EXISTS "anon_select_messages" ON messages;
CREATE POLICY "anon_select_messages" ON messages FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_messages" ON messages;
CREATE POLICY "anon_insert_messages" ON messages FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_messages" ON messages;
CREATE POLICY "anon_update_messages" ON messages FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_messages" ON messages;
CREATE POLICY "anon_delete_messages" ON messages FOR DELETE TO anon, authenticated USING (true);

-- PRDs
CREATE TABLE IF NOT EXISTS prds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  content text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE prds ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_prds_project_id ON prds(project_id);

DROP POLICY IF EXISTS "anon_select_prds" ON prds;
CREATE POLICY "anon_select_prds" ON prds FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_prds" ON prds;
CREATE POLICY "anon_insert_prds" ON prds FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_prds" ON prds;
CREATE POLICY "anon_update_prds" ON prds FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_prds" ON prds;
CREATE POLICY "anon_delete_prds" ON prds FOR DELETE TO anon, authenticated USING (true);

-- Epics
CREATE TABLE IF NOT EXISTS epics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  description text DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);
ALTER TABLE epics ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_epics_project_id ON epics(project_id);

DROP POLICY IF EXISTS "anon_select_epics" ON epics;
CREATE POLICY "anon_select_epics" ON epics FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_epics" ON epics;
CREATE POLICY "anon_insert_epics" ON epics FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_epics" ON epics;
CREATE POLICY "anon_update_epics" ON epics FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_epics" ON epics;
CREATE POLICY "anon_delete_epics" ON epics FOR DELETE TO anon, authenticated USING (true);

-- Tasks
CREATE TABLE IF NOT EXISTS tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  epic_id uuid NOT NULL REFERENCES epics(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  description text DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_tasks_epic_id ON tasks(epic_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks(project_id);

DROP POLICY IF EXISTS "anon_select_tasks" ON tasks;
CREATE POLICY "anon_select_tasks" ON tasks FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_tasks" ON tasks;
CREATE POLICY "anon_insert_tasks" ON tasks FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_tasks" ON tasks;
CREATE POLICY "anon_update_tasks" ON tasks FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_tasks" ON tasks;
CREATE POLICY "anon_delete_tasks" ON tasks FOR DELETE TO anon, authenticated USING (true);

-- Diagrams
CREATE TABLE IF NOT EXISTS diagrams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  mermaid_syntax text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);
ALTER TABLE diagrams ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_diagrams_project_id ON diagrams(project_id);

DROP POLICY IF EXISTS "anon_select_diagrams" ON diagrams;
CREATE POLICY "anon_select_diagrams" ON diagrams FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_diagrams" ON diagrams;
CREATE POLICY "anon_insert_diagrams" ON diagrams FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_diagrams" ON diagrams;
CREATE POLICY "anon_update_diagrams" ON diagrams FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_diagrams" ON diagrams;
CREATE POLICY "anon_delete_diagrams" ON diagrams FOR DELETE TO anon, authenticated USING (true);

-- UI Components
CREATE TABLE IF NOT EXISTS ui_components (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  code text NOT NULL DEFAULT '',
  framework text NOT NULL DEFAULT 'react',
  created_at timestamptz DEFAULT now()
);
ALTER TABLE ui_components ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ui_components_project_id ON ui_components(project_id);

DROP POLICY IF EXISTS "anon_select_ui_components" ON ui_components;
CREATE POLICY "anon_select_ui_components" ON ui_components FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_ui_components" ON ui_components;
CREATE POLICY "anon_insert_ui_components" ON ui_components FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_ui_components" ON ui_components;
CREATE POLICY "anon_update_ui_components" ON ui_components FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_ui_components" ON ui_components;
CREATE POLICY "anon_delete_ui_components" ON ui_components FOR DELETE TO anon, authenticated USING (true);

-- Auto-update updated_at on projects
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_prds_updated_at ON prds;
CREATE TRIGGER trg_prds_updated_at BEFORE UPDATE ON prds
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
